### ISSUE TITLE
Reduce/remove dependency on Tika

### ISSUE THREAD

**Issue by kkrugler** [crawler-commons/http-fetcher#2]
Currently we pull in tika-core so we can use the Metadata type (for http response headers), and for access to one Mime-type extractor routine. We can likely trim down much of the dependent jars, or maybe get rid of the dependency all together and just use the class that we need.

**Comment by lewismc** [comment]
I think that this is a good excuse to raise a ticket over at Tika to split out tika-mime.

**Comment by kkrugler** [comment]
Hi @lewismc - I think the Tika 2.0 plan is to have tika-mime separated, but I don't think they (or I) will do any major refactoring prior to that release.

**Comment by lewismc** [comment]
+1 for copying and borrowing the classes for the time being then Ken

**Comment by aecio** [comment]
Is it ok to copy Tika's `MediaType` class?
I've just pushed a PR that contains this class and replaces Tika's `Metadata` by a simple new `Headers` class.

**Comment by kkrugler** [comment]
Yes, that's fine. It would be good to add a short note to the header that explains where it came from. And don't forget to update the CHANGES.txt file, thanks!

**Comment by kkrugler** [comment]
Just FYI I updated the CHANGES.txt file, but it would be good to still get the (minor) update to Metadata.java.

**Comment by aecio** [comment]
@kkrugler Done.
Thanks.

**Comment by kkrugler** [comment]
Great, thanks @aecio!
